name: Spelling

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@bcf05803b55ef01a5ec6368521ee1b42f97bc438
      - run: make spelling
