name: Spelling

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@a761a4e9afd7b2f353ae020bd6d3a3af34c6c4d5
      - run: make spelling
