name: Spelling

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@c5680ec91f7b9b91406fab4ded5d45245abf7b67
      - run: make spelling
